{"name": "test_tc_001_Creating_User_testing", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "def test_tc_001_Creating_User_testing():\n        print('This is my test case code...')\n        print('Test case is finished...')\n>       assert actual_result == False\nE       assert True == False\n\nAutomationCases\\test_TC_002_Second_Test_case.py:7: AssertionError"}, "attachments": [{"name": "stdout", "source": "a5557668-5853-4c05-bfd6-6da978e8c267-attachment.txt", "type": "text/plain"}], "start": 1674489872576, "stop": 1674489872576, "uuid": "f799fdbb-9483-4163-88fa-33d1ed800635", "historyId": "fbbdd0306585f1ba370990adce5702be", "testCaseId": "3f03bfe916603b901a81112bcd48e1c7", "fullName": "test_TC_002_Second_Test_case#test_tc_001_Creating_User_testing", "labels": [{"name": "suite", "value": "test_TC_002_Second_Test_case"}, {"name": "host", "value": "__VK__"}, {"name": "thread", "value": "3560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_TC_002_Second_Test_case"}]}